# Generated by Django 5.0 on 2024-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='file_name_chinese',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
